server:
  #设置项目访问的上下文，相当于/TBMS 这就是根路径
  servlet:
    context-path: /TBMS
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
  mvc:
    date-format: yyyy-MM-dd
    #配置开启支持put和delete的restful请求
    hiddenmethod:
      filter:
        enabled: true
    #配置开启直接访问templates模板页面权限，不推荐
  #resources:
    #static-locations: classpath:/templates/
  #Springboot不需要导文件上传下载的jar包，默认配置是上传文件不能超过1MB，以下是修改默认配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
      enabled: true

  #mybatis相关配置  mysql8的驱动配置
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectdb?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 83609458
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis包别名扫描
mybatis:
  type-aliases-package: com.zhbit.xiaojiang.entity
  mapper-locations: classpath:com/zhbit/xiaojiang/mapper/*.xml          # mapper映射文件
#mybatis分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql
debug: true