#设置项目访问的上下文，相当于/TBMS 这就是根路径
server:
  servlet:
    context-path: /TBMS
  port: 8081
  tomcat:
    uri-encoding: UTF-8
spring:
  messages:
    basename: i18n.login
  thymeleaf:
    cache: false
    mode: HTML
    encoding: utf-8
  mvc:
    date-format: yyyy-MM-dd
  #配置开启直接访问templates模板页面权限，不推荐
  #resources:
    #static-locations: classpath:/templates/
#debug: true

  #mybatis相关配置
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ProjectDB
    username: root
    password: 83609458
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis包别名扫描
mybatis:
  type-aliases-package: com.zhbit.entity